<a href="https://colab.research.google.com/github/nilotpalc/Python-Training/blob/master/Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [43]:
np.array([[1,2,3],[4,5,6]])
# no of brackets in the array indicate if it is 1D = 1 brac or 2D = 2 brac arrays

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
# this only works for zeros and ones ONLY
np.zeros(3)

array([0., 0., 0.])

In [45]:
# this can be used to create a matrix for zeros and ones ONLY
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
np.arange(5,20,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [47]:
np.linspace(5,20,7)

array([ 5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. ])

In [48]:
np.linspace(5,20,7,dtype = int)

array([ 5,  7, 10, 12, 15, 17, 20])

In [49]:
np.eye(3) # generating an Identity Matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
import numpy as np
from numpy.random import rand
rand(10,2)


array([[0.19169842, 0.58421014],
       [0.77251986, 0.89354181],
       [0.75924951, 0.29819908],
       [0.92704481, 0.56202446],
       [0.16272807, 0.01178487],
       [0.68871945, 0.72390886],
       [0.51091002, 0.27750607],
       [0.76493144, 0.67774574],
       [0.71803575, 0.79017193],
       [0.96361356, 0.22728499]])

In [51]:
import numpy as np
np.random.rand(5,3) # values are between 0 and 1

array([[0.31296605, 0.47746926, 0.08201529],
       [0.25170214, 0.70802855, 0.36111574],
       [0.63299147, 0.68057222, 0.20718086],
       [0.60168302, 0.71393914, 0.72226151],
       [0.38308454, 0.28636751, 0.19947022]])

In [52]:
np.random.randn(3,4) # uses a standard normal distribution with mean Zero and standard deviation 1

array([[-0.85557762, -1.79205852, -2.50182793,  1.2180682 ],
       [-0.71471995,  0.81568707,  1.8325877 , -1.28872163],
       [ 1.10553562,  1.11486806, -0.220363  ,  0.35887542]])

In [53]:
np.random.randint(3,10,5) # generates values between 3 and upto 9.

array([6, 7, 4, 8, 3])

In [54]:
np.random.randint(3,50,(4,6)) # array shape can be specified as a tuple in the argument

array([[25, 18, 28, 23, 30,  6],
       [32, 30, 42, 38, 12, 48],
       [26, 26, 47, 32, 39, 25],
       [ 7,  9, 24, 10,  3,  6]])

In [55]:
arr = np.random.randint(1,50,24)
arr

array([27, 10, 10, 43, 47, 10, 23, 39, 26, 16, 40, 34,  7, 42, 39,  7, 43,
       44,  1,  1, 41, 19, 32, 14])

In [56]:
arr.shape # shape indicates the array design

(24,)

In [57]:
arr2 = arr.reshape(4,6)
arr2

array([[27, 10, 10, 43, 47, 10],
       [23, 39, 26, 16, 40, 34],
       [ 7, 42, 39,  7, 43, 44],
       [ 1,  1, 41, 19, 32, 14]])

In [58]:
arr2.shape

(4, 6)

In [59]:
arr2.reshape(3,8)

array([[27, 10, 10, 43, 47, 10, 23, 39],
       [26, 16, 40, 34,  7, 42, 39,  7],
       [43, 44,  1,  1, 41, 19, 32, 14]])

In [60]:
arr2.max()

47

In [61]:
arr2.argmax() # gives the position of the max number 

4