<a href="https://colab.research.google.com/github/nilotpalc/Python-Training/blob/master/NumPy_Indexing%2CSlicing_and_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy Indexing and Slicing

In [0]:
import numpy as np

In [0]:
arr_2d = np.random.randint(5,50,(4,3))

In [3]:
arr_2d

array([[31, 38, 34],
       [49, 16, 13],
       [44, 15, 28],
       [11, 25, 14]])

In [4]:
arr_2d[1]

array([49, 16, 13])

In [5]:
arr_2d[1:3,1:]

array([[16, 13],
       [15, 28]])

In [6]:
arr_2d[:3]

array([[31, 38, 34],
       [49, 16, 13],
       [44, 15, 28]])

In [7]:
arr_2d[:,2:]  # grab the last column only

array([[34],
       [13],
       [28],
       [14]])

In [8]:
arr_m = arr_2d.reshape(12,)
arr_m

array([31, 38, 34, 49, 16, 13, 44, 15, 28, 11, 25, 14])

In [9]:
arr_m[arr_m > 15]

array([31, 38, 34, 49, 16, 44, 28, 25])

In [10]:
arr_2d[arr_2d > 15]

array([31, 38, 34, 49, 16, 44, 28, 25])

In [11]:
arr_md = np.random.randint(5,50,(3,6))
arr_md

array([[36, 14, 41, 43, 37, 36],
       [49, 10, 22, 22, 18, 12],
       [21, 44, 21, 38, 28, 27]])

In [12]:
arr_md [arr_md > 15]

array([36, 41, 43, 37, 36, 49, 22, 22, 18, 21, 44, 21, 38, 28, 27])

In [14]:
arr_md.shape # returns the row-column as a tuple

(3, 6)

In [0]:
import numpy as np
arr_a = np.arange(50).reshape(5,10)

In [20]:
arr_a[1:4,3:7]

array([[13, 14, 15, 16],
       [23, 24, 25, 26],
       [33, 34, 35, 36]])

In [22]:
np.linspace(5,50,10,dtype=int)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [35]:
arr_a.argmax() # generating the index position of max value in a 2D array

49

# NumPy Operations

In [0]:
arr = np.arange(0,11)

In [24]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [25]:
np.add(arr,arr) # using NumPy in-built functions

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [26]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
np.subtract(arr,arr) # using NumPy in-built functions

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [29]:
np.multiply(arr,arr)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [31]:
np.multiply(arr,2) # using NumPy in-built functions to multiply scalar quantity

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [32]:
np.add(arr,10) # using NumPy in-built functions to multiply scalar quantity

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [33]:
arr + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [34]:
np.power(arr,2) # using NumPy in-built functions to generate square

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])